---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-exporter
  namespace: amazon-cloudwatch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: event-exporter
    namespace: amazon-cloudwatch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-exporter-argo-read
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications", "applicationsets", "appprojects"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-exporter-argo-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: event-exporter-argo-read
subjects:
  - kind: ServiceAccount
    name: event-exporter
    namespace: amazon-cloudwatch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-config
  namespace: amazon-cloudwatch
data:
  config.yaml: |
    logLevel: error
    logFormat: json
    receivers:
      - name: stdout
        file:
          path: /dev/stdout
          layout:
            log: "{{ .Reason }}: {{ .Message }}"
            kubernetes:
              pod_name: "{{ .InvolvedObject.Name }}"
              namespace_name: "{{ .InvolvedObject.Namespace }}"
              container_name: "{{ .InvolvedObject.FieldPath }}"
              reason: "{{ .Reason }}"
              kind: "{{ .InvolvedObject.Kind }}"
    route:
      routes:
        - match:
            - receiver: stdout
              type: Warning
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-exporter
  namespace: amazon-cloudwatch
  labels:
    app: event-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-exporter
  template:
    metadata:
      labels:
        app: event-exporter
    spec:
      serviceAccountName: event-exporter
      containers:
        - name: event-exporter
          image: resmoio/kubernetes-event-exporter:v1.1
          imagePullPolicy: IfNotPresent
          args: ["-conf=/data/config.yaml"]
          volumeMounts:
            - name: config
              mountPath: /data
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: event-exporter-config
