global:
  project: infraguidai
  environment: prod
  region: us-east-1
  namespace: infraguid

  gitRepo: https://github.com/infraGUID/infraguid-argocd.git
  ecrRegistry: 901607650789.dkr.ecr.us-east-1.amazonaws.com
  ecrNamespace: infragui

  awsSecretName: infraguidai/prod/app-secrets

  appRoleArn: arn:aws:iam::901607650789:role/infraguidai-prod-app-irsa

  domain: nutritrack360.in
  acmCertificateArn: arn:aws:acm:us-east-1:901607650789:certificate/5e3e20f5-5666-414c-b5dc-0345e405082b
