name: frontend
namespace: infraguid
replicas: 2
port: 80

image:
  repository: 901607650789.dkr.ecr.us-east-1.amazonaws.com/infragui/frontend
  tag: v1
  pullPolicy: IfNotPresent

cognito:
  userPoolId: us-east-1_6j2IJV8GW
  appClientId: mrp68u2ab77qlirmp15aoaakd
  region: us-east-1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

networkPolicy:
  enabled: true
  allowExternal: true
  ingressFrom: []
  egressTo: []
  egressDNS: true
  egressHTTPS: false
