apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infraguid
  source:
    repoURL: https://github.com/infraGUID/infraguid-argocd.git
    targetRevision: main
    path: argocd-apps/microservices/rag-service
  destination:
    server: https://kubernetes.default.svc
    namespace: infraguid
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
